Shell curvature updates
goma/goma pull request #455
Opened 2024-03-28 13:49 UTC by rbsecor

Added a number of shell curvature options:
 - curvature field advection with Lubrication Curvature Relaxation
 -  option for Petrov-Galerkin on curvature equation with Lubrication Curvature Weight Function
 -  Mass lumping or not with Lubrication Curvature MassLump
 -  option for ls->delta*normal vs. grad_II H in surface tension term

2024-03-28 14:36 UTC, wortiz commented
If you're having clang-format issues the tester is using clang-format-17

You can download a binary here:
https://github.com/llvm/llvm-project/releases/tag/llvmorg-17.0.6

The x86_64-linux one and it will have it under the bin folder or you can use apt to install it https://apt.llvm.org/

2024-03-28 15:09 UTC, rbsecor commented
Thanks!  That was very helpful.

2024-04-02 15:47 UTC, wortiz requested changes

2024-04-02 15:47 UTC, wortiz commented on src/mm_shell_util.c
> +  dbl mu, dmu_dc = 0., dmu_dT = 0., srate = 0.;
Compiler warning dmu_dT set but not used.

2024-04-02 17:38 UTC, wortiz approved these changes

2024-04-02 17:39 UTC, merged