Lubrication Logarithm Interpolation
goma/goma pull request #468
Opened 2024-07-09 02:34 UTC by rbsecor

Added Logarithmic interpolation across the level-set interface for shell lubrication equations.  This seems to make the viscosity behavior for shear-thinning liquids much smoother across the LS interface.

It's invoked via
Lubrication Level-Set Interpolation = LOGARITHMIC
i.e., interpolated value pp = p0^1-H(F) * p1^H(F)

The default is the standard linear interpolation, pp = p0 * (1-H(F)) + p1 * H(F)

At present, only the lubrication flow q(gradP) can be interpolated this way.

2024-07-09 20:46 UTC, rbsecor commented
I probably need to add a test suite problem for LS Logarithmic interpolation... will work on it.

2024-07-10 14:59 UTC, wortiz requested changes

2024-07-10 14:59 UTC, wortiz commented on src/mm_viscosity.c
> +  } else if (model == TIME_RAMP) {
Seems like this accidentally got added twice

2024-07-10 19:07 UTC, wortiz approved these changes

2024-07-19 19:58 UTC, wortiz commented
.runguts

2024-07-24 19:28 UTC, merged